---

# Staging environment
#
# Server port mappings:
#   - ef   6000 (primary/secondary)
#   - prod 7000 (primary/secondary)
#   - scud 8000 (primary/secondary)
#
# Server ID mappings:
#   - ef   0 (primary/secondary)
#   - prod 1 (primary/secondary)
#   - scud 2 (primary/secondary)

informix_server_id_increment: 1
informix_server_id_start: 0
informix_server_port_increment: 1000
informix_server_port_start: 6000

ef_presenter_data:
  enabled: yes
  vault_path: "{{ vault_base_path }}/ef-presenter"

cloudwatch_agent_overrides:
  metrics_enabled: true

informix_service_config:
  ef:
    server_id: "{{ informix_server_id_start + (0 * informix_server_id_increment) | int }}"
    server_port: "{{ informix_server_port_start + (0 * informix_server_port_increment) | int }}"
    dbspaces:
      root:
        initial_chunk:
          path: "{{ informix_chunk_store_path }}/ef/ef_root_dbs_1"
          offset_in_kb: 0
          size_in_kb: 2097152
      ef_data_dbs:
        initial_chunk:
          path: "{{ informix_chunk_store_path }}/ef/ef_data_dbs_1"
          offset_in_kb: 0
          size_in_kb: 8388608
        additional_chunks:
          - path: "{{ informix_chunk_store_path }}/ef/ef_data_dbs_2"
            offset_in_kb: 0
            size_in_kb: 8388608
          - path: "{{ informix_chunk_store_path }}/ef/ef_data_dbs_3"
            offset_in_kb: 0
            size_in_kb: 8388608
      ef_log_dbs:
        initial_chunk:
          path: "{{ informix_chunk_store_path }}/ef/ef_log_dbs_1"
          offset_in_kb: 0
          size_in_kb: 8388608
    server_connections:
        - server_name: ef
          connection_type: onipcshm
          host: localhost
          service_or_port: localhost
        - server_name: ef_primary
          connection_type: onsoctcp
          host: instance-1.fil.tuxedo.staging.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (0 * informix_server_port_increment) | int }}"
        - server_name: ef_secondary
          connection_type: onsoctcp
          host: instance-2.fil.tuxedo.staging.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (0 * informix_server_port_increment) | int }}"
  prod:
    server_id: "{{ informix_server_id_start + (1 * informix_server_id_increment) | int }}"
    server_port: "{{ informix_server_port_start + (1 * informix_server_port_increment) | int }}"
    dbspaces:
      root:
        initial_chunk:
          path: "/dev/prod"
          offset_in_kb: 0
          size_in_kb: 2000000
      prod_data_dbs:
        initial_chunk:
          path: "/dev/prod"
          offset_in_kb: 2000000
          size_in_kb: 7500000
      prod_log_dbs:
        initial_chunk:
          path: "/dev/prod"
          offset_in_kb: 9500000
          size_in_kb: 500000
    server_connections:
        - server_name: prod
          connection_type: onipcshm
          host: localhost
          service_or_port: localhost
        - server_name: prod_primary
          connection_type: onsoctcp
          host: instance-1.fil.tuxedo.staging.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (1 * informix_server_port_increment) | int }}"
        - server_name: prod_secondary
          connection_type: onsoctcp
          host: instance-2.fil.tuxedo.staging.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (1 * informix_server_port_increment) | int }}"
  scud:
    server_id: "{{ informix_server_id_start + (2 * informix_server_id_increment) | int }}"
    server_port: "{{ informix_server_port_start + (2 * informix_server_port_increment) | int }}"
    dbspaces:
      root:
        initial_chunk:
          path: "/dev/scud"
          offset_in_kb: 0
          size_in_kb: 2000000
      scud_data_dbs:
        initial_chunk:
          path: "/dev/scud"
          offset_in_kb: 2000000
          size_in_kb: 7500000
      scud_log_dbs:
        initial_chunk:
          path: "/dev/scud"
          offset_in_kb: 9500000
          size_in_kb: 500000
    server_connections:
        - server_name: scud
          connection_type: onipcshm
          host: localhost
          service_or_port: localhost
        - server_name: scud_primary
          connection_type: onsoctcp
          host: instance-1.fil.tuxedo.staging.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (2 * informix_server_port_increment) | int }}"
        - server_name: scud_secondary
          connection_type: onsoctcp
          host: instance-2.fil.tuxedo.staging.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (2 * informix_server_port_increment) | int }}"

nfsmounts:
  - path: "/DBshare"
    src: "192.168.255.20:/DBshare"

iscsi_devices:
  - alias: db_dump
    raw_character_device_path: /dev/raw/raw1
    filesystem:
      type: xfs
      mount_path: /db_dump
  - alias: scud
    raw_character_device_path: /dev/raw/raw2
  - alias: prod
    raw_character_device_path: /dev/raw/raw3
  - alias: ef
    raw_character_device_path: /dev/raw/raw4
