---

# Live environment
#
# Server port mappings:
#   - ef   6000 (primary/secondary)
#   - prod 7000 (primary/secondary)
#   - scud 8000 (primary/secondary)
#
# Server ID mappings:
#   - ef   0 (primary/secondary)
#   - prod 1 (primary/secondary)
#   - scud 2 (primary/secondary)

sms_poll_daemon_enabled: false

informix_server_id_increment: 1
informix_server_id_start: 0
informix_server_port_increment: 1000
informix_server_port_start: 6000

alerts:
  enabled: yes
  vault_path: "{{ vault_base_path }}/alerts"

stats:
  enabled: yes
  vault_path: "{{ vault_base_path }}/stats"

ef_presenter_data:
  enabled: yes
  vault_path: "{{ vault_base_path }}/ef-presenter"

cloudwatch_agent_overrides:
  metrics_enabled: true

informix_service_config:
  ef:
    server_id: "{{ informix_server_id_start + (0 * informix_server_id_increment) | int }}"
    server_port: "{{ informix_server_port_start + (0 * informix_server_port_increment) | int }}"
    server_aliases: "efliveadmin,efileliveadmin"
    event_alarms_enabled: true
    dbspaces:
      root:
        initial_chunk:
          path: "/dev/ef"
          offset_in_kb: 0
          size_in_kb: 2000000
      ef_data_dbs:
        initial_chunk:
          path: "/dev/ef"
          offset_in_kb: 2000000
          size_in_kb: 17500000
      ef_log_dbs:
        initial_chunk:
          path: "/dev/ef"
          offset_in_kb: 19500000
          size_in_kb: 500000
    server_connections:
        - server_name: ef
          connection_type: onipcshm
          host: localhost
          service_or_port: localhost
        - server_name: ef_primary
          connection_type: onsoctcp
          host: instance-1.fil.tuxedo.live.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (0 * informix_server_port_increment) | int }}"
        - server_name: ef_secondary
          connection_type: onsoctcp
          host: instance-2.fil.tuxedo.live.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (0 * informix_server_port_increment) | int }}"
    users:
      - name: efadmin
  prod:
    server_id: "{{ informix_server_id_start + (1 * informix_server_id_increment) | int }}"
    server_port: "{{ informix_server_port_start + (1 * informix_server_port_increment) | int }}"
    event_alarms_enabled: true
    dbspaces:
      root:
        initial_chunk:
          path: "/dev/prod"
          offset_in_kb: 0
          size_in_kb: 2000000
      prod_data_dbs:
        initial_chunk:
          path: "/dev/prod"
          offset_in_kb: 2000000
          size_in_kb: 7500000
      prod_log_dbs:
        initial_chunk:
          path: "/dev/prod"
          offset_in_kb: 9500000
          size_in_kb: 500000
    server_connections:
        - server_name: prod
          connection_type: onipcshm
          host: localhost
          service_or_port: localhost
        - server_name: prod_primary
          connection_type: onsoctcp
          host: instance-1.fil.tuxedo.live.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (1 * informix_server_port_increment) | int }}"
        - server_name: prod_secondary
          connection_type: onsoctcp
          host: instance-2.fil.tuxedo.live.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (1 * informix_server_port_increment) | int }}"
  scud:
    server_id: "{{ informix_server_id_start + (2 * informix_server_id_increment) | int }}"
    server_port: "{{ informix_server_port_start + (2 * informix_server_port_increment) | int }}"
    server_aliases: "scud_win_svr"
    event_alarms_enabled: true
    dbspaces:
      root:
        initial_chunk:
          path: "/dev/scud"
          offset_in_kb: 0
          size_in_kb: 2000000
      scud_data_dbs:
        initial_chunk:
          path: "/dev/scud"
          offset_in_kb: 2000000
          size_in_kb: 7500000
      scud_log_dbs:
        initial_chunk:
          path: "/dev/scud"
          offset_in_kb: 9500000
          size_in_kb: 500000
    server_connections:
        - server_name: scud
          connection_type: onipcshm
          host: localhost
          service_or_port: localhost
        - server_name: scud_primary
          connection_type: onsoctcp
          host: instance-1.fil.tuxedo.live.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (2 * informix_server_port_increment) | int }}"
        - server_name: scud_secondary
          connection_type: onsoctcp
          host: instance-2.fil.tuxedo.live.heritage.aws.internal
          service_or_port: "{{ informix_server_port_start + (2 * informix_server_port_increment) | int }}"
    users:
      - name: scudadmin

nfsmounts:
  - path: "/home/scud/downloadchd/email"
    src: "192.168.255.35:/chd_image"
  - path: "/home/scud/downloadceu/email"
    src: "192.168.255.35:/chcc_email"
  - path: "/home/scud/downloadwck/email"
    src: "192.168.255.35:/wck_image"
  - path: "/home/scud/downloadceu/post"
    src: "192.168.255.35:/chcc_post"
  - path: "/home/scud/batenvp1"
    src: "192.168.255.35:/batenvp1"
  - path: "/home/ef/wlenvp1letteroutput"
    src: "192.168.255.35:/wlenvp1letteroutput"
  - path: "/data1/apps/scud"
    src: "192.168.255.35:/scanning"
    symlink: "/scanning"
  - path: "/data1/home/scanning"
    src: "/data1/apps/scud/tiffexport"
    opts: "bind"
  - path: "/data1/image/scud"
    src: "/data1/apps/scud/tiffexport"
    opts: "bind"
  - path: "/DBshare"
    src: "192.168.255.35:/DBshare"
  - path: "/mnt/nfs/oltp/input/scud_trans"
    src: "192.168.255.35:/batenvp1/input/scud_trans"
  - path: "/mnt/nfs/oltp/input/scud_pre95"
    src: "192.168.255.35:/batenvp1/input/scud_pre95"
  - path: "/mnt/nfs/oltp/input/shuttle_process"
    src: "192.168.255.35:/batenvp1/input/shuttle_process"
  - path: "/mnt/nfs/oltp/archive/scud_trans"
    src: "192.168.255.35:/batenvp1/archive/scud_trans"
  - path: "/mnt/nfs/oltp/archive/scud_pre95"
    src: "192.168.255.35:/batenvp1/archive/scud_pre95"
  - path: "/mnt/nfs/oltp/archive/shuttle_process"
    src: "192.168.255.35:/batenvp1/archive/shuttle_process"
  - path: "/mnt/nfs/oltp/output/shuttle_process"
    src: "192.168.255.35:/batenvp1/output/shuttle_process"
  - path: "/mnt/nfs/oltp/output/eshuttle_process"
    src: "192.168.255.35:/batenvp1/output/eshuttle_process"
  - path: "/mnt/nfs/image_team_tools"
    src: "192.168.255.35:/image_team_tools"
  - path: "/mnt/nfs/image_team_sql"
    src: "192.168.255.35:/image_team_sql"

iscsi_devices:
  - alias: db_dump
    filesystem:
      type: xfs
      mount_path: /db_dump
  - alias: scud
    raw_character_device_path: /dev/raw/raw1
  - alias: prod
    raw_character_device_path: /dev/raw/raw2
  - alias: ef
    raw_character_device_path: /dev/raw/raw3
