---

- name: Set EC2 metadata facts
  amazon.aws.ec2_metadata_facts:

- name: Check required variables are set
  assert:
    that:
      - scripts_artifact_path is defined and scripts_artifact_path | trim | length > 0
    msg: "Required variable(s) empty or undefined"

- name: Retrieve alerts config from Hashicorp Vault
  set_fact:
    alerts_config: "{{ lookup('community.hashi_vault.hashi_vault', alerts.vault_path) }}"
  when: alerts.enabled

- name: Retrieve stats config from Hashicorp Vault
  set_fact:
    stats_config: "{{ lookup('community.hashi_vault.hashi_vault', stats.vault_path) }}"
  when: stats.enabled

- import_tasks: scripts.yml

- import_tasks: multipath.yml
  when: iscsi_devices is defined

- import_tasks: udev.yml
  when: iscsi_devices is defined

- include_tasks: filesystem.yml
  loop: "{{ iscsi_devices | selectattr('filesystem', 'defined') | list }}"
  loop_control:
    loop_var: device
  when: iscsi_devices is defined
