---

- name: Set EC2 metadata facts
  amazon.aws.ec2_metadata_facts:

- name: Check required variables are set
  assert:
    that:
      - scripts_artifact_path is defined and scripts_artifact_path | trim | length > 0
    msg: "Required variable(s) empty or undefined"

- name: Retrieve alerts config from Hashicorp Vault
  set_fact:
    alerts_config: "{{ lookup('community.hashi_vault.hashi_vault', alerts.vault_path) }}"
  when: alerts.enabled

- name: Retrieve stats config from Hashicorp Vault
  set_fact:
    stats_config: "{{ lookup('community.hashi_vault.hashi_vault', stats.vault_path) }}"
  when: stats.enabled

- name: Create scripts directory
  file:
    path: "/home/{{ informix_user }}/scripts"
    owner: "{{ informix_user }}"
    group: "{{ informix_group }}"
    mode: 0755
    state: directory

- name: "Create Informix maintenance jobs log directory"
  file:
    path: "{{ informix_logs_path }}/common"
    owner: "{{ informix_service_user }}"
    group: "{{ informix_service_group }}"
    mode: 0755
    state: directory

- name: Populate script template files
  template:
    src: "{{ item }}"
    dest: "/home/{{ informix_user }}/scripts/{{ item | basename | replace('.j2', '') }}"
    owner: "{{ informix_user }}"
    group: "{{ informix_group }}"
    mode: 0755
  with_fileglob:
    - "{{ scripts_artifact_path }}/{{ informix_user }}/*.j2"

- name: Create Informix maintenance jobs
  cron:
    name: "{{ item.name }}"
    day: "{{ item.day_of_month }}"
    weekday: "{{ item.day_of_week }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    month: "{{ item.month }}"
    user: "{{ informix_user }}"
    job: "/home/{{ informix_user }}/scripts/{{ item.script }}"
    disabled: "{{ item.disabled | default(false) }}"
  loop: "{{ informix_maintenance_jobs | default([]) }}"

- name: Install additional tools for Informix maintenance scripts
  yum:
    name:
      - bc
      - dialog
      - lzip
      - ncompress
    state: present

- name: Enable interactive menu for Informix user
  blockinfile:
    path: "/home/{{ informix_user }}/.bashrc"
    block: |
      # Display interactive menu on login
      if [[ -f "$HOME/scripts/menu" ]]; then
          source "$HOME/scripts/menu"
          menu
      fi
