---

- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  roles:
    - role: ssh-key
      vars:
        ssh_key_name: ansible_remote
        hashicorp_vault_private_key_path: "{{ vault_base_path }}/aws"

- name: Deploy Tuxedo services
  hosts: aws_ec2
  serial: 1
  remote_user: centos
  become: true
  roles:
    - role: systemd-journald
    - role: aws-cli
      vars:
        aws_cli_temp_dir: "/home/{{ ansible_user }}"
    - role: deploy
