---

- name: Start printer support services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - cups
    - colord

- name: Stop printer support services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - cups
    - colord

- name: Restart Postfix service
  systemd:
    name: postfix
    state: restarted
    enabled: true

- name: Restart systemd-journald service
  systemd:
    name: systemd-journald
    state: restarted
    enabled: true
