---

- name: Start printer support services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - cups
    - colord

- name: Stop printer support services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - cups
    - colord

- name: Restart Postfix service
  systemd:
    name: postfix
    state: restarted
    enabled: yes
