---

- name: Start printer support services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - cups
    - colord

- name: Restart Postfix service
  systemd:
    name: postfix
    state: restarted
    enabled: true
